In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates
import matplotlib.ticker as mtick
from matplotlib.ticker import FormatStrFormatter
from matplotlib.lines import Line2D

from sklearn import metrics

In [2]:
dict_dtypes={'LocationNo': str}
df = pd.read_csv('BuyTitleOfferEval_r42.csv', header=0, dtype=dict_dtypes, index_col=0)

C:\Users\WMiller\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [3]:
df.set_index('CatalogID', drop=True, inplace=True)

In [4]:
df['actual_TotalBuyOffers_R42'] = df['actual_BuyOfferAmt_R42'] * df['count_ItemsPriced']
df['pred_TotalSuggestedOffers_R42'] = df['pred_SuggestedOffer_R42'] * df['count_ItemsPriced']
df['error_AAD_R42'] = df['pred_AAD_R42'] - df['avg_CatalogAccDays_TrashPenalty_R42']
df['RSE_AAD_R42'] = np.sqrt((df['pred_AAD_R42'] - df['avg_CatalogAccDays_TrashPenalty_R42'])**2)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2991908 entries, 4440 to 15409380
Data columns (total 18 columns):
LocationNo                             object
CatalogBinding                         object
count_ItemsPriced                      int64
count_ItemsSold                        int64
avg_CatalogAccDays_TrashPenalty_R42    float64
actual_AvgSalePrice                    float64
actual_BuyGradeName_R42                object
actual_BuyOfferPct_R42                 float64
actual_BuyOfferAmt_R42                 float64
pred_AvgSalePrice                      float64
pred_BuyOfferPct_R42                   float64
pred_SuggestedOffer_R42                float64
pred_AAD_R42                           float64
Date_Generated                         object
actual_TotalBuyOffers_R42              float64
pred_TotalSuggestedOffers_R42          float64
error_AAD_R42                          float64
RSE_AAD_R42                            float64
dtypes: float64(12), int64(2), object(4)
memory usage: 433.7+ MB

In [6]:
filt_Chain = df['LocationNo'] == 'Chain'
df_Chain = df[filt_Chain]#.reset_index(drop=True)
df_Loc = df[~filt_Chain]#.reset_index(drop=True)

In [7]:
# df_Chain['actual_TotalBuyOffers_R42'] = df_Chain['actual_BuyOfferAmt_R42'] * df_Chain['count_ItemsPriced']
# df_Chain['pred_TotalSuggestedOffers_R42'] = df_Chain['pred_SuggestedOffer_R42'] * df_Chain['count_ItemsPriced']
# df_Chain['error_AAD_R42'] = df_Chain['pred_AAD_R42'] - df_Chain['avg_CatalogAccDays_TrashPenalty_R42']
# df_Chain['RSE_AAD_R42'] = np.sqrt((df_Chain['pred_AAD_R42'] - df_Chain['avg_CatalogAccDays_TrashPenalty_R42'])**2)

# df_Loc['actual_TotalBuyOffers_R42'] = df_Loc['actual_BuyOfferAmt_R42'] * df_Loc['count_ItemsPriced']
# df_Loc['pred_TotalSuggestedOffers_R42'] = df_Loc['pred_SuggestedOffer_R42'] * df_Loc['count_ItemsPriced']
# df_Loc['error_AAD_R42'] = df_Loc['pred_AAD_R42'] - df_Loc['avg_CatalogAccDays_TrashPenalty_R42']
# df_Loc['RSE_AAD_R42'] = np.sqrt((df_Loc['pred_AAD_R42'] - df_Loc['avg_CatalogAccDays_TrashPenalty_R42'])**2)

In [8]:
df_Loc

,LocationNo,CatalogBinding,count_ItemsPriced,count_ItemsSold,avg_CatalogAccDays_TrashPenalty_R42,actual_AvgSalePrice,actual_BuyGradeName_R42,actual_BuyOfferPct_R42,actual_BuyOfferAmt_R42,pred_AvgSalePrice,pred_BuyOfferPct_R42,pred_SuggestedOffer_R42,pred_AAD_R42,Date_Generated,actual_TotalBuyOffers_R42,pred_TotalSuggestedOffers_R42,error_AAD_R42,RSE_AAD_R42
CatalogID,,,,,,,,,,,,,,,,,,
4440,00001,General,1,1,10.385,6.49,A,0.40,2.596,4.4957,0.05,0.22,228.539286,2019-04-01,2.596,0.22,218.154286,218.154286
11462,00001,General,1,0,208.350,NaN,D,0.05,NaN,5.2450,0.00,0.00,650.052500,2019-04-01,NaN,0.00,441.702500,441.702500
29544,00001,General,1,1,68.080,2.00,C,0.20,0.400,NaN,NaN,NaN,NaN,NaN,0.400,NaN,NaN,NaN
35084,00001,General,1,1,32.620,4.99,B,0.30,1.497,NaN,NaN,NaN,NaN,NaN,1.497,NaN,NaN,NaN
36169,00001,General,4,1,381.675,2.00,D,0.05,0.100,2.9090,0.05,0.15,308.520909,2019-04-01,0.400,0.60,-73.154091,73.154091
36232,00001,General,1,1,26.715,3.00,B,0.30,0.900,NaN,NaN,NaN,NaN,NaN,0.900,NaN,NaN,NaN
39948,00001,General,1,1,70.355,3.00,C,0.20,0.600,NaN,NaN,NaN,NaN,NaN,0.600,NaN,NaN,NaN
40763,00001,General,1,1,29.210,29.99,B,0.30,8.997,NaN,NaN,NaN,NaN,NaN,8.997,NaN,NaN,NaN
44879,00001,General,1,1,12.895,8.49,A,0.40,3.396,NaN,NaN,NaN,NaN,NaN,3.396,NaN,NaN,NaN
45521,00001,General,2,1,119.035,2.00,C,0.20,0.400,4.5628,0.30,1.37,37.535714,2019-04-01,0.800,2.74,-81.499286,81.499286
48637,00001,CD,1,1,56.990,22.48,C,0.10,2.248,NaN,NaN,NaN,NaN,NaN,2.248,NaN,NaN,NaN
54939,00001,General,1,1,23.795,14.99,B,0.30,4.497,NaN,NaN,NaN,NaN,NaN,4.497,NaN,NaN,NaN
69137,00001,General,1,0,216.940,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70448,00001,Mass Market Paperback,1,1,78.220,1.00,C,0.10,0.100,NaN,NaN,NaN,NaN,NaN,0.100,NaN,NaN,NaN
71312,00001,General,1,0,0.000,NaN,A,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72952,00001,General,1,1,4.930,12.99,A,0.40,5.196,NaN,NaN,NaN,NaN,NaN,5.196,NaN,NaN,NaN
74224,00001,General,1,0,29.970,NaN,B,0.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76126,00001,General,1,1,69.930,8.99,C,0.20,1.798,NaN,NaN,NaN,NaN,NaN,1.798,NaN,NaN,NaN
77896,00001,General,1,0,292.130,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80508,00001,General,1,0,233.390,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89775,00001,General,1,1,4.175,4.99,A,0.40,1.996,4.9672,0.40,1.99,4.793636,2019-04-01,1.996,1.99,0.618636,0.618636
109890,00001,General,1,0,188.950,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110773,00001,General,1,1,70.185,9.99,C,0.20,1.998,NaN,NaN,NaN,NaN,NaN,1.998,NaN,NaN,NaN
117263,00001,General,1,1,89.140,3.00,C,0.20,0.600,3.0000,0.05,0.15,403.745000,2019-04-01,0.600,0.15,314.605000,314.605000
132465,00001,General,1,0,218.330,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133993,00001,General,2,0,441.620,NaN,E,0.00,NaN,3.2425,0.05,0.16,391.662500,2019-04-01,NaN,0.32,-49.957500,49.957500
134707,00001,General,1,1,61.735,6.99,C,0.20,1.398,5.3266,0.20,1.07,131.273333,2019-04-01,1.398,1.07,69.538333,69.538333
134933,00001,General,1,0,217.490,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135191,00001,General,1,1,26.050,3.99,B,0.30,1.197,NaN,NaN,NaN,NaN,NaN,1.197,NaN,NaN,NaN
136451,00001,CD,1,0,172.140,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13810319,00130,General,1,0,76.160,NaN,C,0.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13811346,00130,General,2,0,10.310,NaN,A,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13812051,00130,General,1,0,5.160,NaN,A,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13825586,00130,General,1,0,236.830,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13827046,00130,General,1,1,44.425,2.49,C,0.20,0.498,NaN,NaN,NaN,NaN,NaN,0.498,NaN,NaN,NaN
13985798,00130,General,1,0,0.000,NaN,A,0.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14444170,00130,General,1,0,211.190,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14623485,00130,General,1,1,1.160,14.49,A,0.40,5.796,NaN,NaN,NaN,NaN,NaN,5.796,NaN,NaN,NaN
14687843,00130,General,1,0,320.750,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14695780,00130,General,1,0,331.220,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14741381,00130,General,1,1,6.955,7.49,A,0.40,2.996,NaN,NaN,NaN,NaN,NaN,2.996,NaN,NaN,NaN
14762027,00130,General,1,1,32.830,3.99,B,0.30,1.197,NaN,NaN,NaN,NaN,NaN,1.197,NaN,NaN,NaN
14786889,00130,General,1,1,36.915,14.99,B,0.30,4.497,NaN,NaN,NaN,NaN,NaN,4.497,NaN,NaN,NaN
14804572,00130,General,1,1,49.460,20.00,C,0.20,4.000,NaN,NaN,NaN,NaN,NaN,4.000,NaN,NaN,NaN
15196560,00130,General,1,0,238.200,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15236198,00130,General,1,0,270.060,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15238925,00130,General,1,0,304.250,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15250128,00130,General,1,0,209.860,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15256041,00130,General,1,0,341.570,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15277083,00130,General,1,1,112.070,1.99,C,0.20,0.398,NaN,NaN,NaN,NaN,NaN,0.398,NaN,NaN,NaN
15281384,00130,General,1,1,23.440,3.99,B,0.30,1.197,NaN,NaN,NaN,NaN,NaN,1.197,NaN,NaN,NaN
15281577,00130,General,1,1,49.545,1.00,C,0.20,0.200,NaN,NaN,NaN,NaN,NaN,0.200,NaN,NaN,NaN
15288448,00130,General,1,1,35.040,2.00,B,0.30,0.600,NaN,NaN,NaN,NaN,NaN,0.600,NaN,NaN,NaN
15337242,00130,General,1,1,16.015,5.00,B,0.30,1.500,NaN,NaN,NaN,NaN,NaN,1.500,NaN,NaN,NaN
15386224,00130,General,1,0,238.940,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15423710,00130,General,1,1,54.930,3.00,C,0.20,0.600,NaN,NaN,NaN,NaN,NaN,0.600,NaN,NaN,NaN
15441166,00130,General,1,0,223.800,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15441739,00130,General,1,0,381.070,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15442932,00130,General,1,1,97.525,5.00,C,0.20,1.000,NaN,NaN,NaN,NaN,NaN,1.000,NaN,NaN,NaN
15443061,00130,General,1,0,290.830,NaN,D,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print(df_Chain['count_ItemsPriced'].sum())
print(df_Loc[df_Loc['pred_SuggestedOffer_R42'].isna()]['count_ItemsPriced'].sum())
print(df_Loc[~df_Loc['pred_SuggestedOffer_R42'].isna()]['count_ItemsPriced'].sum())

2285656
2163641
474622

In [11]:
df_All = pd.DataFrame(df.reset_index()['CatalogID'].unique(), columns =['CatalogID']).set_index('CatalogID')#Get all unique catalogIDs in df of all offers, set as index

In [12]:
list_OfferCols = [c for c in df.columns if c not in ['LocationNo', 'CatalogBinding', 'count_ItemsPriced', 'count_ItemsSold']]

In [14]:
filt_ChainOffer = df['LocationNo'] == 'Chain'
#Get all location offers
df_All = df_All.merge(df[~filt_ChainOffer], how='left', left_index=True, right_index=True) 
#Create a filter for where location offers are null
filt_NoLocOffer = (df_All['pred_SuggestedOffer_R42'].isna())
#Where location offers are null, get the offer data columns for chain offers
df_All = df_All[filt_NoLocOffer].merge(df[filt_ChainOffer][list_OfferCols], how='left', left_index=True, right_index=True)

KeyError: 'pred_SuggestedOffer_R42'

In [ ]:
df_All

In [9]:
df_All = df_All.set_index('CatalogID', drop=True)

NameError: name 'df_All' is not defined

In [28]:
df_All[df_All['LocationNo'].isna()] = df_All[df_All['LocationNo'].isna()].combine_first(df_Chain.set_index('CatalogID', drop=True))

NameError: name 'filt_HasLocation' is not defined

In [11]:
filt_ChainOffers = df_All['LocationNo'] == 'Chain'
print(df_All[filt_ChainOffers]['count_ItemsPriced'].sum())
print(df_All[~filt_ChainOffers]['count_ItemsPriced'].sum())

77063.0
1811034.0

In [12]:
def create_PredCompDF(df, minSampleNum, binding='', **kwargs):
    list_Bindings = df['CatalogBinding'].unique()
    if (binding in list_Bindings) == False:
        binding = list_Bindings
    else: 
        binding = [binding]
    filt_QtyNPlus= (df['count_ItemsPriced'] >= minSampleNum) & (df['CatalogBinding'].isin(binding))
    df_PredCompUngrouped = df[filt_QtyNPlus].reset_index(drop=True)
    df_PredComp = df_PredCompUngrouped.groupby(['pred_BuyOfferPct_R42', 'actual_BuyOfferPct_R42']).sum()[['count_ItemsPriced', 'count_ItemsSold']].reset_index()
    return df_PredComp

def calc_CatAcc(df, gradeThreshold=0.3, **kwargs):
    filt_EqualGrades = df['pred_BuyOfferPct_R42'] == df['actual_BuyOfferPct_R42']
    filt_GradeThreshold = df['pred_BuyOfferPct_R42'] >= gradeThreshold
    df_AccByGrade = (df[filt_EqualGrades & filt_GradeThreshold]['count_ItemsPriced'].sum() /
                     df[filt_GradeThreshold]['count_ItemsPriced'].sum())
    return df_AccByGrade

def calc_CatAccByGrade(df):
    filt_EqualGrades = df['pred_BuyOfferPct_R42'] == df['actual_BuyOfferPct_R42']
    df_AccByGrade = pd.DataFrame((df[filt_EqualGrades].groupby('pred_BuyOfferPct_R42').sum()['count_ItemsPriced'] /
                     df.groupby('pred_BuyOfferPct_R42').sum()['count_ItemsPriced']))
    df_AccByGrade= df_AccByGrade.merge(df.groupby('pred_BuyOfferPct_R42').sum()['count_ItemsPriced'], on='pred_BuyOfferPct_R42').reset_index()
    df_AccByGrade.rename(columns={'pred_BuyOfferPct_R42': 'Suggested Offer Grade', 'count_ItemsPriced_x': 'Pct Accuracy', 'count_ItemsPriced_y': 'Total Qty'}, inplace=True)
    return df_AccByGrade

def calc_CatPredPctsByGrade(df, gradeThreshold=0, **kwargs):
    df_PredPctsByGrade = df.merge(df.groupby('pred_BuyOfferPct_R42').sum()['count_ItemsPriced'], on='pred_BuyOfferPct_R42')
    df_PredPctsByGrade['pct_ActualGrades'] = df_PredPctsByGrade['count_ItemsPriced_x'] / df_PredPctsByGrade['count_ItemsPriced_y']
    df_PredPctsByGrade.rename(columns={'pred_BuyOfferPct_R42': 'Suggested Offer Grade', 
                                       'actual_BuyOfferPct_R42': 'Actual Grade',
                                       'count_ItemsPriced_x': 'Qty Actual Grades',
                                       'pct_ActualGrades': 'Pct Actual Grades'}, inplace=True)
    filt_GradeThreshold = df_PredPctsByGrade['Suggested Offer Grade'] >= gradeThreshold
    return df_PredPctsByGrade[filt_GradeThreshold][['Suggested Offer Grade', 'Actual Grade', 'Qty Actual Grades', 'Pct Actual Grades']]

def calc_MRSE(pred, targ):
    mrse = np.sqrt(np.mean([((t - p)**2) for (p, t) in zip(pred, targ)]))
    return mrse

In [13]:
df_Chain.dropna(inplace=True)

In [14]:
#calc_MRSE(df_Chain['avg_CatalogAccDays_NR'], df_Chain['pred_AAD_R42'])

In [15]:
calc_MRSE(df_Chain['avg_CatalogAccDays_TrashPenalty_R42'], df_Chain['pred_AAD_R42'])

519.9604985537806

In [16]:
calc_MRSE(df_Chain['avg_CatalogAccDays_TrashPenalty_R42'], df_Chain['pred_AAD_R42'])

519.9604985537806

In [17]:
filt_Grade = df_Chain['pred_BuyOfferPct_R42'] > 0
filt_QtyThreshold = df_Chain['count_ItemsPriced'] >= 5
filt_Binding = df_Chain['CatalogBinding'] == 'General'

In [18]:
calc_MRSE(df_Chain[filt_Binding & filt_QtyThreshold]['avg_CatalogAccDays_TrashPenalty_R42'], 
          df_Chain[filt_Binding & filt_QtyThreshold]['pred_AAD_R42'])

279.59481983059885

In [19]:
calc_MRSE(df_Chain[filt_Grade & filt_Binding & filt_QtyThreshold]['avg_CatalogAccDays_TrashPenalty_R42'], 
          df_Chain[filt_Grade & filt_Binding & filt_QtyThreshold]['pred_AAD_R42'])

100.90772285960807

In [20]:
df_ChainPredComp = create_PredCompDF(df_Chain[filt_Binding], 5)
print(calc_CatAcc(df_ChainPredComp, gradeThreshold=0))
calc_CatAccByGrade(df_ChainPredComp)

0.651772619878859

   Suggested Offer Grade  Pct Accuracy  Total Qty
0                   0.00      0.483716     102035
1                   0.05      0.661647     355620
2                   0.20      0.747080     460174
3                   0.30      0.548911     173028
4                   0.40      0.309129      36260

In [21]:
calc_CatPredPctsByGrade(df_ChainPredComp, gradeThreshold=0)

    Suggested Offer Grade  Actual Grade  Qty Actual Grades  Pct Actual Grades
0                    0.00          0.00              49356           0.483716
1                    0.00          0.05              48503           0.475356
2                    0.00          0.20               4112           0.040300
3                    0.00          0.30                 64           0.000627
4                    0.05          0.00              28059           0.078902
5                    0.05          0.05             235295           0.661647
6                    0.05          0.20              89766           0.252421
7                    0.05          0.30               2400           0.006749
8                    0.05          0.40                100           0.000281
9                    0.20          0.00               2109           0.004583
10                   0.20          0.05              78784           0.171205
11                   0.20          0.20             343787           0.747080
12                   0.20          0.30              34290           0.074515
13                   0.20          0.40               1204           0.002616
14                   0.30          0.00                256           0.001480
15                   0.30          0.05               3622           0.020933
16                   0.30          0.20              66832           0.386250
17                   0.30          0.30              94977           0.548911
18                   0.30          0.40               7341           0.042427
19                   0.40          0.00                118           0.003254
20                   0.40          0.05                285           0.007860
21                   0.40          0.20               5071           0.139851
22                   0.40          0.30              19577           0.539906
23                   0.40          0.40              11209           0.309129

In [22]:
filt_actual = df_Chain['actual_BuyOfferPct_R42'] == 0.4
filt_pred = df_Chain['pred_BuyOfferPct_R42'] == 0.4
filt_accurate = df_Chain['pred_BuyOfferPct_R42'] == df_Chain['actual_BuyOfferPct_R42']

df_Chain[filt_accurate & filt_pred]['count_ItemsPriced'].sum() / df_Chain[filt_pred]['count_ItemsPriced'].sum()

0.32985104270109233

In [23]:
df_LocPredComp = create_PredCompDF(df_Loc, 1)
print(calc_CatAcc(df_LocPredComp, gradeThreshold=0))
calc_CatAccByGrade(df_LocPredComp)

0.34239036538550677

   Suggested Offer Grade  Pct Accuracy  Total Qty
0                   0.00      0.169284      22542
1                   0.05      0.300692      79583
2                   0.10      0.286093       4149
3                   0.20      0.298865     172613
4                   0.30      0.383205     141222
5                   0.40      0.511218      54513

In [24]:
def create_ConfusionMatrix_Normalized(df):
    df_cm = (df.groupby(['pred_BuyOfferPct_R42', 'actual_BuyOfferPct_R42']).sum()['count_ItemsPriced']/
              df.groupby(['pred_BuyOfferPct_R42']).sum()['count_ItemsPriced'])
    df_cm = df_cm.unstack('actual_BuyOfferPct_R42').fillna(0).stack('actual_BuyOfferPct_R42').sort_index(ascending=False) #Add zeros where nulls result in no index value, sort the index
    idx_order = df_cm.index.levels[0].sort_values(ascending=False)
    array_cm = np.array([np.array(df_cm.loc[i]) for i in idx_order])
    return array_cm

def create_ConfusionMatrix(df):
    df_cm = (df.groupby(['pred_BuyOfferPct_R42', 'actual_BuyOfferPct_R42']).sum()['count_ItemsPriced']/
              df.sum()['count_ItemsPriced'])
    df_cm = df_cm.unstack('actual_BuyOfferPct_R42').fillna(0).stack('actual_BuyOfferPct_R42').sort_index(ascending=False)
    idx_order = df_cm.index.levels[0].sort_values(ascending=False)
    array_cm = ([list(df_cm.loc[i]) for i in idx_order])
    return array_cm

def plot_ConfusionMatrix(cm, max_C = 0, **kwargs):
    fig, ax = plt.subplots(figsize=(8,6))
    if max_C = 0:
        max_C = max([i for j in cm for i in j])
    sns.heatmap(cm, cmap = 'bone', vmin=0, vmax=max_C, annot=True, fmt='.1%', ax=ax)
    ax.set_xlabel('Actual Offer %', fontsize=14)
    ax.set_ylabel('Predicted Offer %', fontsize=14)
    ax.set_xticklabels([ '40%', '30%', '20%', '5%', '0%'])
    ax.set_yticklabels(['40%', '30%', '20%', '5%', '0%'])
    cbar = ax.collections[0].colorbar
    cbar.set_ticks([0, 0.2 * max_C, 0.4 * max_C, 0.6 * max_C, 0.8 * max_C, max_C])
    cbar.set_ticklabels(['{:0.0%}'.format(p) for p in [0, 0.2 * max_C, 0.4 * max_C, 0.6 * max_C, 0.8 * max_C, max_C]])
    #plt.savefig('./R42_ConfMatrix.png')
    plt.show()
    return

SyntaxError: invalid syntax (<ipython-input-24-4e4d247bc84e>, line 19)

In [ ]:
filt_QtyThreshold = df_Chain['count_ItemsPriced'] >= 5
filt_Binding = df_Chain['CatalogBinding'] == 'General'

In [ ]:
df_ChainPredComp = create_PredCompDF(df_Chain[filt_Binding], 5)
print(calc_CatAcc(df_ChainPredComp, gradeThreshold=0))
calc_CatAccByGrade(df_ChainPredComp)

In [ ]:
fig, ax = plt.subplots(figsize=(8,6))
C = create_ConfusionMatrix_Normalized(df_Chain[filt_Binding & filt_QtyThreshold])
# C = metrics.confusion_matrix(df_Chain[filt_Binding & filt_QtyThreshold]['actual_BuyOfferPct_R42'].astype(str), 
#                              df_Chain[filt_Binding & filt_QtyThreshold]['pred_BuyOfferPct_R42'].astype(str), 
#                                      labels=['0.4', '0.3', '0.2', '0.05', '0.0'])
sns.heatmap(C, cmap = 'bone', vmin=0, vmax=1, annot=True, fmt='.1%', ax=ax)
ax.set_xlabel('Actual Offer %', fontsize=14)
ax.set_ylabel('Predicted Offer %', fontsize=14)
ax.set_xticklabels([ '40%', '30%', '20%', '5%', '0%'])
ax.set_yticklabels(['40%', '30%', '20%', '5%', '0%'])
cbar = ax.collections[0].colorbar
cbar.set_ticks([0, 0.2, 0.4, 0.6, 0.8, 1])
cbar.set_ticklabels(['0%', '20%', '40%', '60%', '80%', '100%'])
#plt.savefig('./R42_NormConfMatrix.png')
plt.show()

In [ ]:
fig, ax = plt.subplots(figsize=(8,6))
C = create_ConfusionMatrix(df_Chain[filt_Binding & filt_QtyThreshold])
# C = metrics.confusion_matrix(df_Chain[filt_Binding & filt_QtyThreshold]['actual_BuyOfferPct_R42'].astype(str), 
#                              df_Chain[filt_Binding & filt_QtyThreshold]['pred_BuyOfferPct_R42'].astype(str), 
#                                      labels=['0.4', '0.3', '0.2', '0.05', '0.0'])
max_C = max([i for j in C for i in j])
sns.heatmap(C, cmap = 'bone', vmin=0, vmax=max_C, annot=True, fmt='.1%', ax=ax)
ax.set_xlabel('Actual Offer %', fontsize=14)
ax.set_ylabel('Predicted Offer %', fontsize=14)
ax.set_xticklabels([ '40%', '30%', '20%', '5%', '0%'])
ax.set_yticklabels(['40%', '30%', '20%', '5%', '0%'])
cbar = ax.collections[0].colorbar
cbar.set_ticks([0, 0.2 * max_C, 0.4 * max_C, 0.6 * max_C, 0.8 * max_C, max_C])
cbar.set_ticklabels(['{:0.0%}'.format(p) for p in [0, 0.2 * max_C, 0.4 * max_C, 0.6 * max_C, 0.8 * max_C, max_C]])
#plt.savefig('./R42_ConfMatrix.png')
plt.show()

In [ ]:
filt_LocNAPreds = df_Loc['pred_SuggestedOffer_R42'].isna()
filt_LocQtyThreshold = df_Loc['count_ItemsPriced'] >= 5
filt_LocBinding = df_Loc['CatalogBinding'] == 'General'
cm = create_ConfusionMatrix(df_Loc[~filt_LocNAPreds &filt_LocBinding & filt_LocQtyThreshold])
plot_ConfusionMatrix(cm)

In [ ]:
print((df_Chain[filt_Binding & filt_QtyThreshold]['actual_BuyOfferAmt_R42'] * 
       df_Chain[filt_Binding & filt_QtyThreshold]['count_ItemsPriced']).sum())

print((df_Chain[filt_Binding & filt_QtyThreshold]['pred_SuggestedOffer_R42'] * 
       df_Chain[filt_Binding & filt_QtyThreshold]['count_ItemsPriced']).sum())

print((df_Chain[filt_Binding & filt_QtyThreshold]['actual_BuyOfferAmt_R42'] * 
       df_Chain[filt_Binding & filt_QtyThreshold]['count_ItemsPriced']).sum() -
     (df_Chain[filt_Binding & filt_QtyThreshold]['pred_SuggestedOffer_R42'] * 
       df_Chain[filt_Binding & filt_QtyThreshold]['count_ItemsPriced']).sum())

print((df_Chain[filt_Binding & filt_QtyThreshold]['pred_SuggestedOffer_R42'] * 
       df_Chain[filt_Binding & filt_QtyThreshold]['count_ItemsPriced']).sum()/
     (df_Chain[filt_Binding & filt_QtyThreshold]['actual_BuyOfferAmt_R42'] * 
      df_Chain[filt_Binding & filt_QtyThreshold]['count_ItemsPriced']).sum())

In [ ]:
df_Chain['actual_TotalBuyOffers_R42'] = df_Chain['actual_BuyOfferAmt_R42'] * df_Chain['count_ItemsPriced']
df_Chain['pred_TotalSuggestedOffers_R42'] = df_Chain['pred_SuggestedOffer_R42'] * df_Chain['count_ItemsPriced']
df_Chain['error_AAD_R42'] = df_Chain['pred_AAD_R42'] - df_Chain['avg_CatalogAccDays_TrashPenalty_R42']
df_Chain['RSE_AAD_R42'] = np.sqrt((df_Chain['pred_AAD_R42'] - df_Chain['avg_CatalogAccDays_TrashPenalty_R42'])**2)

In [ ]:
df_Chain[filt_Binding].groupby('pred_BuyOfferPct_R42')['actual_TotalBuyOffers_R42', 'pred_TotalSuggestedOffers_R42'].sum()

In [ ]:
sns.set_style('whitegrid')
fig, ax = plt.subplots(figsize=(8,6))
sns.regplot(df_Chain[filt_Binding & filt_QtyThreshold]['pred_AAD_R42'],
            df_Chain[filt_Binding & filt_QtyThreshold]['error_AAD_R42'],
            scatter_kws=dict(alpha=0.1),
            line_kws=dict(color='grey'))
ax.set_xlim([0,5000])
ax.set_ylim([-2500,2500])
ax.set_xlabel('Predicted Total Day Accumulation w/ Trash Penalty')
ax.set_ylabel('Predicted minus Actual Day Accumulation')
#plt.savefig('./R42_ContinuousErrorRegPlot.png')
plt.show()

In [ ]:
sns.set_style('whitegrid')
fig, ax = plt.subplots(figsize=(8,6))
sns.regplot(df_Chain[filt_Binding & filt_QtyThreshold]['pred_AAD_R42'],
            df_Chain[filt_Binding & filt_QtyThreshold]['RSE_AAD_R42'],
            scatter_kws=dict(alpha=0.1),
            line_kws=dict(color='grey'))
ax.set_xlim([0,5000])
ax.set_ylim([0,5000])
ax.set_xlabel('Predicted Title Day Accumulation w/ Trash Penalty')
ax.set_ylabel('Prediction RMSE')
#plt.savefig('./R42_ContinuousRSERegPlot.png')
plt.show()

In [ ]:
df_plt = df_Chain[filt_Binding][['pred_AAD_R42', 'RSE_AAD_R42']]
df_plt['pred_AAD_R42'] = round(df_plt['pred_AAD_R42'], 0)
sns.set_style('whitegrid')
fig, ax = plt.subplots(figsize=(8,6))
sns.scatterplot(df_plt.groupby('pred_AAD_R42')['pred_AAD_R42'].mean(),
                df_plt.groupby('pred_AAD_R42')['RSE_AAD_R42'].mean(),
                ax = ax)
ax.set_xlim([0, 500])
ax.set_ylim([0, 400])
ax.set_xlabel('Predicted Day Accumulation')
ax.set_ylabel('Root Mean Squared Error')
#plt.savefig('./R42_ContinuousRMSE_500Scale.png')
plt.show()

In [ ]:
df_plt = df_Chain[filt_Binding][['pred_AAD_R42', 'RSE_AAD_R42']]
df_plt['pred_AAD_R42'] = round(df_plt['pred_AAD_R42'], 0)
sns.set_style('whitegrid')
fig, ax = plt.subplots(figsize=(8,6))
sns.scatterplot(df_plt.groupby('pred_AAD_R42')['pred_AAD_R42'].mean(),
                df_plt.groupby('pred_AAD_R42')['RSE_AAD_R42'].mean(),
                ax = ax)
ax.set_xlim([0, 500])
ax.set_ylim([0, 500])
ax.set_xlabel('Predicted Day Accumulation')
ax.set_ylabel('Root Mean Squared Error')
#plt.savefig('./R42_ContinuousRMSE_200Scale.png')
plt.show()

In [ ]:
df_Chain.groupby('pred_BuyOfferPct_R42')['RSE_AAD_R42'].mean()

In [ ]:
df_Chain.groupby('pred_BuyOfferPct_R42')['RSE_AAD_R42'].median()

In [ ]:
fig, ax = plt.subplots(figsize=(12,8))
sns.boxplot(x='pred_BuyOfferPct_R42', y='RSE_AAD_R42', order=[0.4, 0.3, 0.2, 0.05, 0.0], data=df_Chain[filt_Binding], ax=ax, boxprops=dict(alpha=.5))
sns.violinplot(x='pred_BuyOfferPct_R42', y='RSE_AAD_R42', order=[0.4, 0.3, 0.2, 0.05, 0.0], data=df_Chain[filt_Binding], ax=ax)
ax.set_ylim(0,2000)
ax.set_xlabel('Buy Offer Percetages')
ax.set_xticklabels([ '40%', '30%', '20%', '5%', '0%'])
ax.set_ylabel('Variance')
ax.yaxis.set_major_locator(mtick.MultipleLocator(100))
#plt.savefig('./R42_ErrorsByGrade_VioBox.png')
ax.set_title('Title Day Accumulation Prediction Error by Grade', fontsize=16)
plt.show()

In [ ]:
df_Chain.info()

In [ ]:

(df_Chain.groupby(['pred_BuyOfferPct_R42', 'actual_BuyOfferPct_R42']).sum()['count_ItemsPriced']/
 df_Chain.groupby(['pred_BuyOfferPct_R42']).sum()['count_ItemsPriced']).sort_values(ascending=False)

In [ ]:
df_Chain.info()